### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by afc163** [insiight/ant-design-theme-builder#2]
Modify primary color, click update button and nothing changed.

**Comment by neekey** [comment]
hmm...it's working on my side, can you provide your browser version?

**Comment by afc163** [comment]
I just found it is my mistake for updating a wrong input to change primary color.

<img width="201" alt="image" src="https://user-images.githubusercontent.com/507615/30434250-58d9d130-9999-11e7-863b-66c2fe322a74.png">

I modified the @info-color input which I thought it is @primary-color and nothing changed so I was confused. 😆

**Comment by neekey** [comment]
No worries : )
